### ISSUE TITLE
Cannot remove builds with references (e.g. in errata)

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#115]
If we try to delete this: https://build.almalinux.org/build/5466 , we will see the error show below.
This happens because we don’t use cascade deletion for `errata_to_albs_packages` table.

```
web_server_1                 | Traceback (most recent call last):
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 442, in _prepare_and_execute
web_server_1                 |     self._rows = await prepared_stmt.fetch(*parameters)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
web_server_1                 |     data = await self.__bind_execute(args, 0, timeout)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
web_server_1                 |     data, status, _ = await self.__do_execute(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
web_server_1                 |     return await executor(protocol)
web_server_1                 |   File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
web_server_1                 | asyncpg.exceptions.ForeignKeyViolationError: update or delete on table "build_artifacts" violates foreign key constraint "errata_to_albs_packages_albs_artifact_id_fkey" on table "errata_to_albs_packages"
web_server_1                 | DETAIL:  Key (id)=(1693104) is still referenced from table "errata_to_albs_packages".
web_server_1                 | 
web_server_1                 | The above exception was the direct cause of the following exception:
web_server_1                 | 
web_server_1                 | Traceback (most recent call last):
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
web_server_1                 |     self.dialect.do_execute(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
web_server_1                 |     cursor.execute(statement, parameters)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
web_server_1                 |     self._adapt_connection.await_(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
web_server_1                 |     return current.driver.switch(awaitable)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
web_server_1                 |     value = await result
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
web_server_1                 |     self._handle_exception(error)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
web_server_1                 |     self._adapt_connection._handle_exception(error)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
web_server_1                 |     raise translated_error from error
web_server_1                 | sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.IntegrityError: <class 'asyncpg.exceptions.ForeignKeyViolationError'>: update or delete on table "build_artifacts" violates foreign key constraint "errata_to_albs_packages_albs_artifact_id_fkey" on table "errata_to_albs_packages"
web_server_1                 | DETAIL:  Key (id)=(1693104) is still referenced from table "errata_to_albs_packages".
web_server_1                 | 
web_server_1                 | The above exception was the direct cause of the following exception:
web_server_1                 | 
web_server_1                 | Traceback (most recent call last):
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
web_server_1                 |     result = await app(self.scope, self.receive, self.send)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
web_server_1                 |     return await self.app(scope, receive, send)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/fastapi/applications.py", line 261, in __call__
web_server_1                 |     await super().__call__(scope, receive, send)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
web_server_1                 |     await self.middleware_stack(scope, receive, send)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
web_server_1                 |     raise exc
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
web_server_1                 |     await self.app(scope, receive, _send)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
web_server_1                 |     raise exc
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
web_server_1                 |     await self.app(scope, receive, sender)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
web_server_1                 |     raise exc
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
web_server_1                 |     await self.app(scope, receive, sender)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
web_server_1                 |     raise e
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
web_server_1                 |     await self.app(scope, receive, send)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
web_server_1                 |     await route.handle(scope, receive, send)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
web_server_1                 |     await self.app(scope, receive, send)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
web_server_1                 |     response = await func(request)
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
web_server_1                 |     raw_response = await run_endpoint_function(
web_server_1                 |   File "/code/env/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
web_server_1                 |     return await dependant.call(**values)
web_server_1                 |   File "/code/./alws/routers/builds.py", line 112, in remove_build
web_server_1                 |     await build_crud.remove_build_job(db, build_id)
web_server_1                 |   File "/code/./alws/crud/build.py", line 272, in remove_build_job
web_server_1                 |     await db.execute(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 212, in execute
web_server_1                 |     result = await greenlet_spawn(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 134, in greenlet_spawn
web_server_1                 |     result = context.throw(*sys.exc_info())
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/orm/session.py", line 1692, in execute
web_server_1                 |     result = conn._execute_20(statement, params or {}, execution_options)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
web_server_1                 |     return meth(self, args_10style, kwargs_10style, execution_options)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
web_server_1                 |     return connection._execute_clauseelement(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
web_server_1                 |     ret = self._execute_context(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
web_server_1                 |     self._handle_dbapi_exception(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
web_server_1                 |     util.raise_(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
web_server_1                 |     raise exception
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
web_server_1                 |     self.dialect.do_execute(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
web_server_1                 |     cursor.execute(statement, parameters)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
web_server_1                 |     self._adapt_connection.await_(
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
web_server_1                 |     return current.driver.switch(awaitable)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
web_server_1                 |     value = await result
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
web_server_1                 |     self._handle_exception(error)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
web_server_1                 |     self._adapt_connection._handle_exception(error)
web_server_1                 |   File "/code/env/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
web_server_1                 |     raise translated_error from error
web_server_1                 | sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: update or delete on table "build_artifacts" violates foreign key constraint "errata_to_albs_packages_albs_artifact_id_fkey" on table "errata_to_albs_packages"
web_server_1                 | DETAIL:  Key (id)=(1693104) is still referenced from table "errata_to_albs_packages".
web_server_1                 | [SQL: DELETE FROM build_artifacts WHERE build_artifacts.id IN (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
web_server_1                 | [parameters: (1693044, 1693045, 1693046, 1693047, 1693048, 1693049, 1693050, 1693051, 1693052, 1693053, 1693054, 1693055, 1693056, 1693057, 1693058, 1693059, 1693060, 1693061, 1693062, 1693063, 1693082, 1693083, 1693084, 1693085, 1693086, 1693087, 1693088, 1693089, 1693090, 1693091, 1693092, 1693093, 1693094, 1693095, 1693096, 1693097, 1693098, 1693099, 1693100, 1693101, 1693102, 1693103, 1693104, 1693105, 1693106, 1693107, 1693108, 1693064, 1693065, 1693066, 1693067, 1693068, 1693069, 1693070, 1693071, 1693072, 1693073, 1693074, 1693075, 1693076, 1693077, 1693078, 1693079, 1693080, 1693081)]
web_server_1                 | (Background on this error at: https://sqlalche.me/e/14/gkpj)

```

**Comment by forbiddenpotato** [comment]
another example: https://build.almalinux.org/build/7016

**Comment by Korulag** [comment]
https://github.com/AlmaLinux/albs-web-server/pull/658
