### ISSUE TITLE
Investigate the issue with building AL8 S390X

### ISSUE THREAD

**Issue by soksanichenko** [AlmaLinux/build-system#129]
Lorax raises strange exception
```
2023-10-23 23:51:52,547:   install images/install.img images
  install images/install.img images
2023-10-23 23:51:52,547:   OSError: nothing matching /var/tmp/lorax/lorax.1j_tpfz1/installroot/images/install.img in /
  OSError: nothing matching /var/tmp/lorax/lorax.1j_tpfz1/installroot/images/install.img in /
Traceback (most recent call last):
  File "/usr/sbin/lorax", line 207, in <module>
    main()
  File "/usr/sbin/lorax", line 203, in main
    squashfs_only=opts.squashfs_only)
  File "/usr/lib/python3.6/site-packages/pylorax/__init__.py", line 369, in run
    treebuilder.build()
  File "/usr/lib/python3.6/site-packages/pylorax/treebuilder.py", line 346, in build
    self._runner.run(templatefile, kernels=self.kernels)
  File "/usr/lib/python3.6/site-packages/pylorax/ltmpl.py", line 147, in run
    self._run(commands)
  File "/usr/lib/python3.6/site-packages/pylorax/ltmpl.py", line 166, in _run
    f(*args)
  File "/usr/lib/python3.6/site-packages/pylorax/ltmpl.py", line 293, in install
    for src in rglob(self._in(srcglob), fatal=True):
  File "/usr/lib/python3.6/site-packages/pylorax/ltmpl.py", line 103, in rglob
    raise IOError("nothing matching %s in %s" % (pathname, root))
OSError: nothing matching /var/tmp/lorax/lorax.1j_tpfz1/installroot/images/install.img in /
2023-10-23 23:51:52,548: Cleaning up tempdir - /var/tmp/lorax/lorax.1j_tpfz1
[root@almalinux_8_s390x ~]#
```

**Comment by soksanichenko** [comment]
The root of issue is no enough space on storage. Therefor `mksquashfs` can't build an image.
