### ISSUE TITLE
Show user the reason why build not created

### ISSUE THREAD

**Issue by forbiddenpotato** [AlmaLinux/build-system#18]
Sometimes a build is not created without fault on side of a user. That happens because of unhandled errors on backend. In that case user see blank screen.

Acceptance Criteria:
* If error is occurred and can't be negated by backend, message is shown to user with human readable description of error and how to get around it
* If error can be negated by backend (i.e. by retrying of something), backend have to try. On fail go to 1.

![Image](https://github.com/AlmaLinux/build-system/assets/135831959/4f4c4a1c-bba9-42b5-b92d-ada6b403f6a5)
```
Traceback (most recent call last):
  File "/code/env/lib/python3.9/site-packages/dramatiq/worker.py", line 485, in process_message
    res = actor(*message.args, **message.kwargs)
  File "/code/env/lib/python3.9/site-packages/dramatiq/actor.py", line 177, in __call__
    return self.fn(*args, **kwargs)
  File "/code/./alws/dramatiq/build.py", line 151, in start_build
    event_loop.run_until_complete(_start_build(build_id, parsed_build))
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/code/./alws/dramatiq/build.py", line 71, in _start_build
    await planner.add_task(task)
  File "/code/./alws/build_planner.py", line 390, in add_task
    raise EmptyBuildError
alws.errors.EmptyBuildError
[2023-03-11 07:56:00,119] [PID 10] [Thread-6] [dramatiq.middleware.retries.Retries] [WARNING] Retries exceeded for message 'dc391e4e-5c53-4e14-9066-9fd933a4f521'.
[2023-03-11 07:56:17,216] [PID 14] [Thread-6] [root] [ERROR] Cannot get multilib packages, trying next reference platform
```

**Comment by anfimovdm** [comment]
https://github.com/AlmaLinux/albs-web-server/pull/573
