### ISSUE TITLE
git-cacher: design is too optimistic to make thousands of HTTP requests

### ISSUE THREAD

**Issue by metalefty** [AlmaLinux/build-system#183]
It seems the current code of git cache try to retrieve information of all rpms, after that add it to cache. 

If some kind of failure occurs, such as connection timeout, even the information that was successfully retrieved will not be cached. Even one error during retrieving thousands of rpms information prevents rerieved information cached at all.  The git cacher container restarts after the failure and starts to retrieve information from the beginning. The container will restart again if some error occured again.  This repeats forever until no errors occurred while thousands of requests.

I think it is too optimistic to expect no errors occur during tons of HTTP requests.  It is also waste of resources to retry tons of requests from the beginning.

```
2024-02-08 08:22:03,761 [gitea-cacher:DEBUG] - Making new request https://git.almalinux.org/api/v1/repos/rpms/buildah/branches, with params: {'limit': 50, 'page': 1}
2024-02-08 08:22:05,308 [gitea-cacher:DEBUG] - Making new request https://git.almalinux.org/api/v1/repos/rpms/criu/tags, with params: {'limit': 50, 'page': 2}
2024-02-08 08:22:05,793 [gitea-cacher:DEBUG] - Making new request https://git.almalinux.org/api/v1/repos/rpms/custodia/branches, with params: {'limit': 50, 'page': 1}
2024-02-08 08:22:05,976 [gitea-cacher:DEBUG] - Making new request https://git.almalinux.org/api/v1/repos/rpms/crun/tags, with params: {'limit': 50, 'page': 2}
2024-02-08 08:22:06,278 [gitea-cacher:DEBUG] - Making new request https://git.almalinux.org/api/v1/repos/rpms/Cython/branches, with params: {'limit': 50, 'page': 1}
2024-02-08 08:22:06,665 [gitea-cacher:DEBUG] - Making new request https://git.almalinux.org/api/v1/repos/rpms/criu/branches, with params: {'limit': 50, 'page': 1}
2024-02-08 08:22:07,141 [gitea-cacher:DEBUG] - Making new request https://git.almalinux.org/api/v1/repos/rpms/crun/branches, with params: {'limit': 50, 'page': 1}
2024-02-08 08:22:07,697 [gitea-cacher:DEBUG] - Making new request https://git.almalinux.org/api/v1/repos/rpms/ecj/branches, with params: {'limit': 50, 'page': 1}
Traceback (most recent call last):
  File "/code/env/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "git_cacher.py", line 113, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "git_cacher.py", line 105, in main
    await asyncio.gather(
  File "git_cacher.py", line 76, in run
    results = await asyncio.gather(
  File "/code/alws/utils/gitea.py", line 90, in index_repo
    tags = await self.list_tags(repo_name)
  File "/code/alws/utils/gitea.py", line 79, in list_tags
    return await self._list_all_pages(endpoint)
  File "/code/alws/utils/gitea.py", line 66, in _list_all_pages
    response = await self.make_request(endpoint, payload)
  File "/code/alws/utils/gitea.py", line 52, in make_request
    async with session.get(full_url, params=params) as response:
  File "/code/env/lib/python3.8/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
  File "/code/env/lib/python3.8/site-packages/aiohttp/client.py", line 562, in _request
    conn = await self._connector.connect(
  File "/code/env/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/code/env/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/code/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/code/env/lib/python3.8/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/code/env/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host git.almalinux.org:443 ssl:default [None]
```

Fortnately, there are not so many modules. Module information are cached successfully.

```
$ redis-cli
127.0.0.1:6379> keys *
1) "modules_gitea_cache"
```

**Comment by metalefty** [comment]
PR: https://github.com/AlmaLinux/albs-web-server/pull/717
