### ISSUE TITLE
No module named 'google.api'

### ISSUE THREAD

**Issue by m10k** [AlmaLinux/build-system#232]
When executing alma-sbom on a clean AlmaLinux 9 machine, I'm getting the following error (after running `python3 setup.py install`).
```
(env) [root@alma-sbom-env alma-sbom]# ./alma_sbom.py --help
Traceback (most recent call last):
  File "/root/alma-sbom/./alma_sbom.py", line 13, in <module>
    from immudb_wrapper import ImmudbWrapper
  File "<frozen zipimport>", line 259, in load_module
  File "/root/alma-sbom/env/lib64/python3.9/site-packages/immudb_wrapper-0.1.1-py3.9.egg/immudb_wrapper.py", line 15, in <module>
  File "/root/alma-sbom/env/lib64/python3.9/site-packages/immudb_py-1.4.0-py3.9.egg/immudb/__init__.py", line 13, in <module>
    from immudb.client import ImmudbClient
  File "/root/alma-sbom/env/lib64/python3.9/site-packages/immudb_py-1.4.0-py3.9.egg/immudb/client.py", line 18, in <module>
    from immudb import grpcutils
  File "/root/alma-sbom/env/lib64/python3.9/site-packages/immudb_py-1.4.0-py3.9.egg/immudb/grpcutils.py", line 20, in <module>
    import immudb.grpc.schema_pb2_grpc as schema_pb2_grpc
  File "/root/alma-sbom/env/lib64/python3.9/site-packages/immudb_py-1.4.0-py3.9.egg/immudb/grpc/schema_pb2_grpc.py", line 6, in <module>
    from . import schema_pb2 as schema__pb2
  File "/root/alma-sbom/env/lib64/python3.9/site-packages/immudb_py-1.4.0-py3.9.egg/immudb/grpc/schema_pb2.py", line 16, in <module>
    from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
ModuleNotFoundError: No module named 'google.api'
```

According to `pip3 freeze`, the following dependencies are installed:
```
alma-sbom==0.0.2
appier==1.31.4
beartype==0.16.4
boolean.py==4.0
cachetools==5.3.2
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
cyclonedx-python-lib==2.7.1
dataclasses==0.8
ecdsa==0.18.0
gitdb==4.0.11
GitPython==3.1.29
google-api==0.1.12
google-api-core==2.15.0
google-auth==2.25.1
googleapis-common-protos==1.62.0
grpcio==1.60.0
idna==3.6
immudb-py==1.4.0
immudb-wrapper==0.1.1
isodate==0.6.1
license-expression==30.2.0
packageurl-python==0.10.3
ply==3.11
protobuf==3.20.3
pyasn1==0.5.1
pyasn1-modules==0.3.0
pyparsing==3.1.1
PyYAML==6.0.1
rdflib==7.0.0
requests==2.31.0
rsa==4.9
semantic-version==2.10.0
six==1.16.0
smmap==5.0.1
sortedcontainers==2.4.0
spdx-tools==0.8.0
toml==0.10.2
uritools==4.0.2
urllib3==1.26.18
xmltodict==0.13.0
```

I have another (older) environment, which is still working. This environment has the following packages installed:
```
alma-sbom==0.0.1
appier==1.31.4
beartype==0.15.0
boolean.py==4.0
cachetools==5.3.2
cas-wrapper==0.0.6
certifi==2023.5.7
charset-normalizer==3.1.0
click==8.1.3
cyclonedx-python-lib==2.7.1
dataclasses==0.8
ecdsa==0.18.0
gitdb==4.0.10
GitPython==3.1.29
google-api==0.1.12
google-api-core==2.14.0
google-auth==2.23.4
googleapis-common-protos==1.61.0
grpcio==1.60.0rc1
idna==3.4
immudb-py==1.4.0
immudb-wrapper==0.1.2
isodate==0.6.1
license-expression==30.1.1
packageurl-python==0.10.3
plumbum==1.8.1
ply==3.11
protobuf==3.20.3
pyasn1==0.5.0
pyasn1-modules==0.3.0
pyparsing==3.0.9
PyYAML==6.0
rdflib==6.3.2
requests==2.30.0
rsa==4.9
semantic-version==2.10.0
six==1.16.0
smmap==5.0.0
sortedcontainers==2.4.0
spdx-tools==0.8.0
toml==0.10.2
UNKNOWN==0.0.0
uritools==4.0.1
urllib3==2.0.2
xmltodict==0.13.0
```

I tried downgrading some of the google packages, and while that fixed the problem with `google.api`, it caused a similar error for `google.protobuf`. Both environments have the same alma-sbom and immudb-wrapper installed, so something in the dependencies must have changed.

**Comment by javihernandez** [comment]
@KAWAHARA-souta can you check if https://github.com/AlmaLinux/immudb-wrapper/pull/8 fixes the issue for you?

**Comment by KAWAHARA-souta** [comment]
Thank you for your work @javihernandez !!
It looks OK for me.
