### ISSUE TITLE
Error when trying to release approved errata packages

### ISSUE THREAD

**Issue by javihernandez** [AlmaLinux/build-system#380]
When I try to release approved errata packages, I'm getting the following problem:

```
vendor.4ee03438.js:6 SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Proxy.createRelease (732.c6d3cd0e.js:1:542)
    at Proxy.created (732.c6d3cd0e.js:1:453)
    at i (vendor.4ee03438.js:6:11233)
    at a (vendor.4ee03438.js:6:11300)
    at ze (vendor.4ee03438.js:8:8088)
    at Ie (vendor.4ee03438.js:8:7425)
    at ro (vendor.4ee03438.js:8:39395)
    at no (vendor.4ee03438.js:8:38906)
    at to (vendor.4ee03438.js:8:38524)
```

I checked the code around and looks like the router is no longer passing the arguments to the component.
* The arguments are sent [here](https://github.com/AlmaLinux/albs-frontend/blob/master/src/components/ErrataInfo.vue#L1035)
* The router processes them [like this](https://github.com/AlmaLinux/albs-frontend/blob/master/src/router/routes.js#L135)
* And the component is expecting them [here](https://github.com/AlmaLinux/albs-frontend/blob/master/src/pages/ErrataRelease.vue#L14)

Looks like this is broken since long time ago, or that the issue was caused by a recent update of our dependencies.

**Comment by javihernandez** [comment]
This has not been working since we got vue-router 4.1.4, see [the following changelog](https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22).
