### ISSUE TITLE
cas_wrapper should stop raising exception when an artifact is not notarized

### ISSUE THREAD

**Issue by javihernandez** [AlmaLinux/build-system#46]
Whenever an artifact is not notarized, build nodes raise the following error:

```
Unexpected exit code: 2
Command line: | /usr/local/bin/cas authenticate git:///srv/alternatives/castor/build_node/builder-2/133807/git_sources -o json
Stderr:       | 
              | Warning: fbd6087820958a67ba62f6b19b4777aa64f46ff70620e37bc87aaab622ef0d22 was not notarized
```

And we can see it propagated in this [build log](https://build.almalinux.org/build/6924/logs/133675?project_name=python2&arch=i686) like this:

```
07:51:23 30.06.23 ERROR   ]: Cannot authenticate: git:///srv/alternatives/castor/build_node/builder-0/133675/git_sources
Traceback (most recent call last):
  File "/home/albs-builder/.albs_venv/lib64/python3.6/site-packages/cas_wrapper.py", line 133, in authenticate
    result_of_execution = command()
  File "/home/albs-builder/.albs_venv/lib64/python3.6/site-packages/plumbum/commands/base.py", line 99, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/albs-builder/.albs_venv/lib64/python3.6/site-packages/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/home/albs-builder/.albs_venv/lib64/python3.6/site-packages/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/home/albs-builder/.albs_venv/lib64/python3.6/site-packages/plumbum/commands/processes.py", line 322, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/home/albs-builder/.albs_venv/lib64/python3.6/site-packages/plumbum/commands/processes.py", line 24, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/albs-builder/.albs_venv/lib64/python3.6/site-packages/plumbum/machines/base.py", line 29, in verify
    getattr(self, "argv", None), self.returncode, stdout, stderr
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 2
Command line: | /usr/local/bin/cas authenticate git:///srv/alternatives/castor/build_node/builder-0/133675/git_sources -o json
Stderr:       | 
              | Warning: bbf8ee5265ded7c10213af6a2ffc435b4708051e81179757ebcf3b7daa277a9f was not notarized
```

This is not an error but a warning, it's okay that an artifact is not notarized.

We need to update the [cas_wrapper](https://git.almalinux.org/almalinux/cas_wrapper/) to avoid raising such exception and log a warning instead.
I imagine it'll be a matter of disabling the exit-code validation when running commands through plumbum.

**Comment by forbiddenpotato** [comment]
we changed implementation
